#!/bin/bash

if [ $# -eq 0 ]
then
    echo "usage: $0 <shutdown-deferrer url>"
    exit 1
fi

poll_interval=5
poll_timeout=600
shutdown_deferrer_url=$1

# Poll shutdown-deferrer service in order to wait for proper node draining
# before shutdown.
defer="true"
while [ "$defer" = "true" -a $poll_timeout -gt 0 ]
do
    sleep $poll_interval
    defer=$(/usr/bin/curl -qsS $shutdown_deferrer_url)
    echo "GET /v1/defer: $defer"
    poll_timeout=$(/usr/bin/expr $poll_timeout - $poll_interval)
done

# Return successful exit status to k8s
exit 0
